package it.clever.spring.tutorial.business.entities;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.List;

import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * AuthGroup generated by hbm2java
 */
@Entity
@Table(name = "auth_groups", 
		uniqueConstraints = @UniqueConstraint(columnNames = "group_name"))
@Cacheable
@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
public class AuthGroup implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	
	@Version
	@Column(name = "version")
	private Integer version;
	
	@Column(name = "description", length = 45)
	private String description;
	
	@Column(name = "group_name", unique = true, length = 45)
	private String groupName;
	
	@OneToMany(fetch=FetchType.LAZY)
	@JoinColumn(name="group")
	private List<User> users;

	// Caricamento EAGER dei grant.
	@ManyToMany(fetch=FetchType.EAGER)
	@JoinTable(
		name="auth_group_authorities"
		, joinColumns={
			@JoinColumn(name="group_id", nullable=false)
			}
		, inverseJoinColumns={
			@JoinColumn(name="authority", nullable=false)
			}
		)
	private List<AuthAuthorities> authAuthorities;
	

	public AuthGroup() {
	}

	public AuthGroup(String description, String groupName) {
		this.description = description;
		this.groupName = groupName;
	}


	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}


	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	public List<User> getUsers() {
		return users;
	}

	public void setUsers(List<User> groups) {
		this.users = groups;
	}

	public List<AuthAuthorities> getAuthAuthorities() {
		return authAuthorities;
	}

	public void setAuthAuthorities(List<AuthAuthorities> authAuthorities) {
		this.authAuthorities = authAuthorities;
	}

	@Override
	public String toString() {
		return "AuthGroup [id=" + id + ", description=" + description
				+ ", groupName=" + groupName + "]";
	}

	
}
