// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package it.clever.opengest.business.domain;

import it.clever.opengest.business.domain.Order;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Order_Roo_Configurable {
    
    declare @type: Order: @Configurable;
    
}
