package it.clever.hibernate.tutorial.business.entity;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Cascade;
//import javax.persistence.CascadeType;
import org.hibernate.annotations.CascadeType;


/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "clienti", catalog = "opengest")
public class Customer extends BaseEntity implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_cliente", unique = true, nullable = false)
	private Integer idCliente;
	
	@Column(name = "codice", nullable = false, length = 45)
	private String codice;

	@Column(name = "rag_soc", nullable = false, length = 45)
	private String ragSoc;
	
	@Column(name = "piva", nullable = false, length = 16277215)
	private String piva;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
        @Cascade({CascadeType.DELETE})
	private Set<Order> orders = new HashSet<Order>(0);

	@OneToOne(mappedBy = "customer")
	@Cascade({CascadeType.SAVE_UPDATE, CascadeType.ALL})
	private CustomerContract contract;
	
	public Customer() {
	}

	public Customer(String codice, String ragSoc, String piva) {
		this.codice = codice;
		this.ragSoc = ragSoc;
		this.piva = piva;
	}

	public Customer(String codice, String ragSoc, String piva,
			Set<Order> ordinis) {
		this.codice = codice;
		this.ragSoc = ragSoc;
		this.piva = piva;
		this.orders = ordinis;
	}

	public Integer getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(Integer idCliente) {
		this.idCliente = idCliente;
	}

	public String getCodice() {
		return this.codice;
	}

	public void setCodice(String codice) {
		this.codice = codice;
	}
	
	public String getRagSoc() {
		return this.ragSoc;
	}

	public void setRagSoc(String ragSoc) {
		this.ragSoc = ragSoc;
	}

	public String getPiva() {
		return this.piva;
	}

	public void setPiva(String piva) {
		this.piva = piva;
	}

	public Set<Order> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Order> ordinis) {
		this.orders = ordinis;
	}

	public CustomerContract getContract() {
		return contract;
	}

	public void setContract(CustomerContract contract) {
		this.contract = contract;
	}

}
